# Generated by Django 3.1.4 on 2021-05-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberImports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_datetime', models.DateTimeField(auto_now_add=True, unique=True)),
                ('active_members', models.PositiveIntegerField()),
                ('new_members', models.PositiveIntegerField()),
                ('unsubscribed_members', models.PositiveIntegerField()),
                ('changed_members', models.PositiveIntegerField()),
            ],
        ),
    ]
