# Generated by Django 3.1.4 on 2021-05-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0002_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='last_memberimport',
            field=models.DateField(null=True),
        ),
    ]
