# Generated by Django 3.1.4 on 2021-06-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0004_configuration_refresh_all'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberImports',
            new_name='MemberImport',
        ),
    ]
