# Generated by Django 3.1.4 on 2021-06-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0005_auto_20210603_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatiecode', models.CharField(max_length=7, unique=True)),
                ('voorletters', models.CharField(blank=True, max_length=10)),
                ('roepnaam', models.CharField(blank=True, max_length=25)),
                ('tussenvoegsels', models.CharField(blank=True, max_length=10)),
                ('achternaam', models.CharField(blank=True, max_length=50)),
                ('geslacht', models.CharField(choices=[('M', 'Man'), ('V', 'Vrouw')], default='M', max_length=1)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('straatnaam', models.CharField(blank=True, max_length=50)),
                ('huisnummer', models.IntegerField(blank=True, null=True)),
                ('toevoeging', models.CharField(blank=True, max_length=10)),
                ('postcode', models.CharField(blank=True, max_length=7)),
                ('plaats', models.CharField(blank=True, max_length=30)),
                ('telefoon', models.CharField(blank=True, max_length=15)),
                ('mobiel', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('A', 'afgemeld'), ('D', 'definitief'), ('O', 'overschrijving spelactiviteit'), ('Q', 'overschrijving spelactiviteit (aspirant)')], max_length=1)),
                ('afmelddatum', models.DateField(blank=True)),
                ('wijziging', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'configuration', 'verbose_name_plural': 'configurations'},
        ),
        migrations.AlterModelOptions(
            name='memberimport',
            options={'verbose_name': 'member import', 'verbose_name_plural': 'member imports'},
        ),
        migrations.AlterField(
            model_name='configuration',
            name='last_memberimport',
            field=models.DateField(null=True, verbose_name='last member import'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='refresh_all',
            field=models.BooleanField(default=False, verbose_name='refresh all'),
        ),
        migrations.AlterField(
            model_name='memberimport',
            name='active_members',
            field=models.PositiveIntegerField(verbose_name='active members'),
        ),
        migrations.AlterField(
            model_name='memberimport',
            name='changed_members',
            field=models.PositiveIntegerField(verbose_name='changes'),
        ),
        migrations.AlterField(
            model_name='memberimport',
            name='import_datetime',
            field=models.DateTimeField(auto_now_add=True, unique=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='memberimport',
            name='new_members',
            field=models.PositiveIntegerField(verbose_name='new registrations'),
        ),
        migrations.AlterField(
            model_name='memberimport',
            name='unsubscribed_members',
            field=models.PositiveIntegerField(verbose_name='unsubscribes'),
        ),
    ]
