# Generated by Django 3.1.4 on 2021-06-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0006_auto_20210606_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberimport',
            name='non_active_members',
            field=models.PositiveIntegerField(default=0, verbose_name='non active members'),
            preserve_default=False,
        ),
    ]
