# Generated by Django 3.1.4 on 2021-06-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0007_memberimport_non_active_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='wijziging',
        ),
        migrations.AddField(
            model_name='member',
            name='last_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.memberimport'),
        ),
        migrations.AddField(
            model_name='member',
            name='leeftijdscategorie',
            field=models.CharField(default='Senioren', max_length=10),
            preserve_default=False,
        ),
    ]
