# Generated by Django 3.1.4 on 2021-06-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0008_auto_20210613_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberimport',
            name='active_members',
            field=models.PositiveIntegerField(default=0, verbose_name='active members'),
        ),
        migrations.AlterField(
            model_name='memberimport',
            name='changed_members',
            field=models.PositiveIntegerField(default=0, verbose_name='changes'),
        ),
        migrations.AlterField(
            model_name='memberimport',
            name='new_members',
            field=models.PositiveIntegerField(default=0, verbose_name='new registrations'),
        ),
        migrations.AlterField(
            model_name='memberimport',
            name='non_active_members',
            field=models.PositiveIntegerField(default=0, verbose_name='non active members'),
        ),
        migrations.AlterField(
            model_name='memberimport',
            name='unsubscribed_members',
            field=models.PositiveIntegerField(default=0, verbose_name='unsubscribes'),
        ),
    ]
