# Generated by Django 3.1.4 on 2021-06-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0009_auto_20210613_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AlterField(
            model_name='member',
            name='leeftijdscategorie',
            field=models.CharField(max_length=25),
        ),
    ]
