# Generated by Django 3.1.4 on 2021-06-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0010_auto_20210613_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='afmelddatum',
        ),
    ]
