# Generated by Django 3.1.4 on 2021-06-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0011_remove_member_afmelddatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='aanmeldingsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='geslacht',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('V', 'Veld'), ('Z', 'Zaal'), ('D', 'Donateur')], max_length=1)),
                ('base_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kledingfonds', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kortingcode', models.CharField(blank=True, choices=[('25', '25% lid'), ('50', '50% lid'), ('SP', 'Gesponsord'), ('BL', 'Korting vanwege blessure'), ('AR', 'Speciale regeling')], max_length=2)),
                ('kortingadres', models.CharField(blank=True, choices=[('25', '25% lid'), ('50', '50% lid'), ('SP', 'Gesponsord'), ('BL', 'Korting vanwege blessure'), ('AR', 'Speciale regeling')], max_length=2)),
                ('kortingpercentage', models.PositiveIntegerField(default=0)),
                ('kortingopdatum', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('contribution', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('contribution_payed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment_method', models.CharField(choices=[('I', 'Automatische incasso'), ('F', 'Factuur'), ('C', 'Contant'), ('H', 'Huygenspas'), ('J', 'Jeugdsportfonds')], max_length=1)),
                ('iban', models.CharField(blank=True, max_length=18)),
                ('factuur_naam', models.CharField(blank=True, max_length=50)),
                ('factuur_adres', models.CharField(blank=True, max_length=50)),
                ('factuur_postcode', models.CharField(blank=True, max_length=7)),
                ('factuur_plaats', models.CharField(blank=True, max_length=30)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jarrbo_contributie.member')),
            ],
            options={
                'unique_together': {('member', 'activity')},
            },
        ),
    ]
