# Generated by Django 3.1.4 on 2021-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0012_auto_20210613_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lidnr', models.IntegerField(unique=True)),
                ('tenaamstelling', models.CharField(max_length=30)),
                ('achternaam', models.CharField(blank=True, max_length=50)),
                ('vrvg', models.CharField(blank=True, max_length=10)),
                ('vrls', models.CharField(blank=True, max_length=10)),
                ('voornaam', models.CharField(max_length=25)),
                ('adres', models.CharField(max_length=50)),
                ('postcd', models.CharField(max_length=7)),
                ('woonpl', models.CharField(max_length=30)),
                ('reknr', models.CharField(blank=True, max_length=18)),
                ('gebdat', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='status_code',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AddIndex(
            model_name='rddata',
            index=models.Index(fields=['achternaam', 'voornaam', 'gebdat'], name='jarrbo_cont_achtern_53450b_idx'),
        ),
    ]
