# Generated by Django 3.1.4 on 2021-06-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0013_auto_20210620_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='rddata',
            name='activity',
            field=models.CharField(default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='rddata',
            name='lidnr',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='rddata',
            unique_together={('lidnr', 'activity')},
        ),
    ]
