# Generated by Django 3.1.4 on 2021-06-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0014_auto_20210621_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='rddata',
            name='huygens',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rddata',
            name='tenaamstelling',
            field=models.CharField(max_length=50),
        ),
    ]
