# Generated by Django 3.1.4 on 2021-06-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0015_auto_20210621_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1)),
                ('leeftijdscategoriecategory', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kledingfonds', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
