# Generated by Django 3.1.4 on 2021-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0016_contributiontable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributiontable',
            old_name='amount',
            new_name='base_contribution',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='kortingadres',
        ),
        migrations.AddField(
            model_name='contribution',
            name='kortingopadres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
