# Generated by Django 3.1.4 on 2021-06-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0017_auto_20210622_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='seizoen_startjr',
            field=models.PositiveIntegerField(default=False, verbose_name='season start year'),
        ),
    ]
