# Generated by Django 3.1.4 on 2021-06-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0018_configuration_seizoen_startjr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributiontable',
            old_name='leeftijdscategoriecategory',
            new_name='leeftijdscategorie',
        ),
        migrations.AddField(
            model_name='contribution',
            name='aanmaningskosten',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='contribution',
            name='administratiekosten',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='contributiontable',
            name='seizoen',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='contributiontable',
            unique_together={('seizoen', 'activity', 'leeftijdscategorie')},
        ),
    ]
