# Generated by Django 3.1.4 on 2021-06-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0020_auto_20210623_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seizoen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seizoenstartjaar', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='seizoen_startjr',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.member'),
        ),
        migrations.AlterField(
            model_name='contributiontable',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.activity'),
        ),
        migrations.AlterField(
            model_name='contributiontable',
            name='leeftijdscategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.leeftijdscategory'),
        ),
        migrations.AlterField(
            model_name='member',
            name='leeftijdscategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.leeftijdscategory'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='seizoen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.seizoen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='seizoen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.seizoen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributiontable',
            name='seizoen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.seizoen'),
        ),
    ]
