# Generated by Django 3.1.4 on 2021-06-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0021_auto_20210623_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='seizoen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.seizoen'),
        ),
    ]
