# Generated by Django 3.1.4 on 2021-06-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0022_auto_20210623_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='seizoen',
        ),
    ]
