# Generated by Django 3.1.4 on 2021-06-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0023_remove_configuration_seizoen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='seizoen',
        ),
    ]
