# Generated by Django 3.1.4 on 2021-06-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0024_remove_contribution_seizoen'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='seizoen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.seizoen'),
        ),
    ]
