# Generated by Django 3.1.4 on 2021-06-24 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0025_configuration_seizoen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Longcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longcategory', models.CharField(max_length=25)),
                ('leeftijdscategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.leeftijdscategory')),
            ],
        ),
    ]
