# Generated by Django 3.1.4 on 2021-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0026_longcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leeftijdscategory',
            name='description',
            field=models.CharField(max_length=25),
        ),
    ]
