# Generated by Django 3.1.4 on 2021-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0027_auto_20210624_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longcategory',
            name='longcategory',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
