# Generated by Django 3.1.4 on 2021-06-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0028_auto_20210624_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='seizoen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.seizoen'),
        ),
    ]
