# Generated by Django 3.1.4 on 2021-06-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0029_contribution_seizoen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.activity'),
        ),
        migrations.AlterField(
            model_name='rddata',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.activity'),
        ),
    ]
