# Generated by Django 3.1.4 on 2021-06-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0030_auto_20210624_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paymentstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('submitdate', models.DateField(blank=True)),
                ('paymentdate', models.DateField(blank=True)),
                ('withdrawndate', models.DateField(blank=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.contribution')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.paymentmethod')),
                ('seizoen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.seizoen')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.paymentstatus')),
            ],
        ),
    ]
