# Generated by Django 3.1.4 on 2021-06-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0031_payment_paymentmethod_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.paymentmethod'),
        ),
    ]
