# Generated by Django 3.1.4 on 2021-06-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0032_auto_20210624_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
    ]
