# Generated by Django 3.1.4 on 2021-06-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0033_remove_activity_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='base_contribution',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='kledingfonds',
        ),
    ]
