# Generated by Django 3.1.4 on 2021-06-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0034_auto_20210624_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kortingtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='kortingcode',
        ),
        migrations.AddField(
            model_name='contribution',
            name='kortingtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.kortingtype'),
        ),
    ]
