# Generated by Django 3.1.4 on 2021-06-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0035_auto_20210624_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='kortingtype',
        ),
        migrations.DeleteModel(
            name='Kortingtype',
        ),
    ]
