# Generated by Django 3.1.4 on 2021-06-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0037_auto_20210624_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentbatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('seizoen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.seizoen')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentbatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.paymentbatch'),
        ),
    ]
