# Generated by Django 3.1.4 on 2021-06-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0038_auto_20210625_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seizoen',
            options={'ordering': ['startjaar'], 'verbose_name': 'season', 'verbose_name_plural': 'seasons'},
        ),
        migrations.RenameField(
            model_name='seizoen',
            old_name='seizoenstartjaar',
            new_name='startjaar',
        ),
        migrations.RemoveField(
            model_name='seizoen',
            name='description',
        ),
    ]
