# Generated by Django 3.1.4 on 2021-06-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0039_auto_20210628_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['description'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='leeftijdscategory',
            options={'ordering': ['category'], 'verbose_name': 'age category', 'verbose_name_plural': 'age categories'},
        ),
        migrations.AddField(
            model_name='leeftijdscategory',
            name='maximum_age',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
