# Generated by Django 3.1.4 on 2021-06-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0040_auto_20210628_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leeftijdscategory',
            options={'ordering': ['-maximum_age'], 'verbose_name': 'age category', 'verbose_name_plural': 'age categories'},
        ),
    ]
