# Generated by Django 3.1.4 on 2021-06-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0042_auto_20210628_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['achternaam', 'tussenvoegsels', 'roepnaam'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AlterModelOptions(
            name='memberimport',
            options={'ordering': ['-import_datetime'], 'verbose_name': 'member import', 'verbose_name_plural': 'member imports'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['description'], 'verbose_name': 'payment method', 'verbose_name_plural': 'payment methods'},
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['relatiecode'], name='jarrbo_cont_relatie_d47aed_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['postcode'], name='jarrbo_cont_postcod_c2be1e_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['geboortedatum'], name='jarrbo_cont_geboort_d29a6a_idx'),
        ),
    ]
