# Generated by Django 3.1.4 on 2021-06-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0043_auto_20210628_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['member', 'activity'], 'verbose_name': 'contribution', 'verbose_name_plural': 'contributions'},
        ),
        migrations.AlterModelOptions(
            name='contributiontable',
            options={'ordering': ['seizoen', 'activity', 'leeftijdscategorie'], 'verbose_name': 'contribution table', 'verbose_name_plural': 'contribution tables'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['seizoen', 'contribution', 'paymentbatch'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentbatch',
            options={'ordering': ['seizoen', 'datum'], 'verbose_name': 'payment batch', 'verbose_name_plural': 'payment batches'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name': 'payment status', 'verbose_name_plural': 'payment status'},
        ),
    ]
