# Generated by Django 3.1.4 on 2021-06-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0044_auto_20210628_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='termijnen',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
