# Generated by Django 3.1.4 on 2021-06-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0045_contribution_termijnen'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_import'], name='jarrbo_cont_last_im_d93329_idx'),
        ),
    ]
