# Generated by Django 3.1.4 on 2021-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0046_auto_20210628_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='kortingpercentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
