# Generated by Django 3.1.4 on 2021-06-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0047_member_kortingpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rddata',
            name='kortingpercentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
