# Generated by Django 3.1.4 on 2021-06-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0048_rddata_kortingpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='adres_machtiging',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='huygenspas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='iban',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='member',
            name='machtiging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='naam_machtiging',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='plaats_machtiging',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='member',
            name='postcode_machtiging',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
