# Generated by Django 3.1.4 on 2021-06-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0049_auto_20210628_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbatch',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
