# Generated by Django 3.1.4 on 2021-06-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0050_paymentbatch_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inschrijving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumtijd', models.DateTimeField(unique=True)),
                ('roepnaam', models.CharField(max_length=50)),
                ('achternaam', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
                ('woonplaats', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=7)),
                ('geboortedatum', models.DateField()),
                ('machtiging', models.BooleanField(default=False)),
                ('naam_machtiging', models.CharField(max_length=50)),
                ('adres_machtiging', models.CharField(max_length=50)),
                ('postcode_machtiging', models.CharField(max_length=7)),
                ('plaats_machtiging', models.CharField(max_length=30)),
                ('iban', models.CharField(blank=True, max_length=18)),
                ('privacy_policy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machtiging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumtijd', models.DateTimeField(unique=True)),
                ('voornaam', models.CharField(max_length=50)),
                ('achternaam', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
                ('woonplaats', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=7)),
                ('geboortedatum', models.DateField()),
                ('naam_machtiging', models.CharField(max_length=50)),
                ('plaats_machtiging', models.CharField(max_length=30)),
                ('iban', models.CharField(blank=True, max_length=18)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='rddata',
            name='jarrbo_cont_achtern_53450b_idx',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='administratiekosten',
        ),
        migrations.AddIndex(
            model_name='rddata',
            index=models.Index(fields=['gebdat', 'postcd'], name='jarrbo_cont_gebdat_95b712_idx'),
        ),
        migrations.AddIndex(
            model_name='machtiging',
            index=models.Index(fields=['geboortedatum', 'postcode'], name='jarrbo_cont_geboort_85f3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='inschrijving',
            index=models.Index(fields=['geboortedatum', 'postcode'], name='jarrbo_cont_geboort_06db53_idx'),
        ),
        migrations.AddField(
            model_name='member',
            name='inschrijving',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.inschrijving'),
        ),
    ]
