# Generated by Django 3.1.4 on 2021-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0051_auto_20210629_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plaats_machtiging',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
