# Generated by Django 3.1.4 on 2021-06-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0052_auto_20210630_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='inschrijving',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.inschrijving'),
        ),
    ]
