# Generated by Django 3.1.4 on 2021-06-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0053_auto_20210630_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inschrijving',
            name='datumtijd',
            field=models.DateTimeField(),
        ),
    ]
