# Generated by Django 3.1.4 on 2021-06-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0054_auto_20210630_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='inschrijving',
            name='webform',
            field=models.BooleanField(default=False),
        ),
    ]
