# Generated by Django 3.1.4 on 2021-06-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0055_inschrijving_webform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inschrijving',
            name='datumtijd',
            field=models.DateTimeField(null=True),
        ),
    ]
