# Generated by Django 3.1.4 on 2021-07-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0056_auto_20210630_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='include',
            field=models.BooleanField(default=False),
        ),
    ]
