# Generated by Django 3.1.4 on 2021-07-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0057_paymentstatus_include'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='kortingopdatum',
        ),
    ]
