# Generated by Django 3.1.4 on 2021-07-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0058_remove_contribution_kortingopdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='jarrbo_contributie.contribution'),
        ),
    ]
