# Generated by Django 3.1.4 on 2021-07-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0059_auto_20210702_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='createdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='submitdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='withdrawndate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
