# Generated by Django 3.1.4 on 2021-07-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0062_auto_20210703_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='leeftijdscategorie',
        ),
    ]
