# Generated by Django 3.1.4 on 2021-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0063_remove_member_leeftijdscategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status_code',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
    ]
