# Generated by Django 3.1.4 on 2021-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0064_auto_20210704_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
