# Generated by Django 3.1.4 on 2021-07-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0065_paymentmethod_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='active',
            field=models.BooleanField(default=True, help_text='The members actively executes payments'),
        ),
    ]
