# Generated by Django 3.1.4 on 2021-07-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0066_auto_20210710_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsstatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.paymentmethod')),
                ('statusafter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changeafter', to='jarrbo_contributie.paymentstatus')),
                ('statusbefore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changebefore', to='jarrbo_contributie.paymentstatus')),
            ],
        ),
    ]
