# Generated by Django 3.1.4 on 2021-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0067_paymentsstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsstatuschange',
            name='activemethod',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='paymentsstatuschange',
            unique_together={('statusbefore', 'activemethod', 'statusafter')},
        ),
        migrations.RemoveField(
            model_name='paymentsstatuschange',
            name='method',
        ),
    ]
