# Generated by Django 3.1.4 on 2021-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0068_auto_20210710_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='description',
            field=models.CharField(default='Must be filled', max_length=15),
            preserve_default=False,
        ),
    ]
