# Generated by Django 3.1.4 on 2021-07-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0069_paymentstatus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='description',
            field=models.CharField(max_length=25),
        ),
    ]
