# Generated by Django 3.1.4 on 2021-07-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0070_auto_20210711_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentsstatusChange',
            new_name='PaymentstatusChange',
        ),
    ]
