# Generated by Django 3.1.4 on 2021-07-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0071_auto_20210711_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'payment type',
                'verbose_name_plural': 'payment types',
                'ordering': ['type'],
            },
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='active',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.paymenttype'),
        ),
        migrations.AddField(
            model_name='paymentstatuschange',
            name='paymenttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.paymenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentstatuschange',
            unique_together={('paymenttype', 'statusbefore', 'statusafter')},
        ),
        migrations.RemoveField(
            model_name='paymentstatuschange',
            name='activemethod',
        ),
    ]
