# Generated by Django 3.1.4 on 2021-07-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0073_auto_20210711_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='ak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='contribution',
            name='bc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='contribution',
            name='kd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='contribution',
            name='kdp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contribution',
            name='kf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='contribution',
            name='ks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='contribution',
            name='tc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='member',
            name='lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.leeftijdscategory'),
        ),
    ]
