# Generated by Django 3.1.4 on 2021-07-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0074_auto_20210713_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentbatchStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'paymentbatch status',
                'verbose_name_plural': 'paymentbatch status',
            },
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.paymentbatchstatus'),
        ),
    ]
