# Generated by Django 3.1.4 on 2021-07-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0075_auto_20210715_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentbatch',
            name='submitted',
        ),
    ]
