# Generated by Django 3.1.4 on 2021-07-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0076_remove_paymentbatch_submitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['seizoen', 'contribution__member__achternaam', 'contribution__member__tussenvoegsels', 'contribution__member__roepnaam'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
