# Generated by Django 3.1.4 on 2021-07-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0077_auto_20210715_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='rddata',
            name='insdat',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentbatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='jarrbo_contributie.paymentbatch'),
        ),
    ]
