# Generated by Django 3.1.4 on 2021-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0078_auto_20210720_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inschrijvingsdatum',
            field=models.DateTimeField(null=True),
        ),
    ]
