# Generated by Django 3.1.4 on 2021-07-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0079_member_inschrijvingsdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='machtiging_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
