# Generated by Django 3.1.4 on 2021-07-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0080_member_machtiging_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
