# Generated by Django 3.1.4 on 2021-07-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0082_auto_20210721_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='kortingvast',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
