# Generated by Django 3.1.4 on 2021-07-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0085_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentbatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='jarrbo_contributie.paymentbatch'),
        ),
    ]
