# Generated by Django 3.1.4 on 2021-07-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0086_auto_20210722_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['seizoen', 'contribution__member__achternaam', 'contribution__member__tussenvoegsels', 'contribution__member__roepnaam', 'paymentdate'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
