# Generated by Django 3.1.4 on 2021-07-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0087_auto_20210723_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_machtiging',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
