# Generated by Django 3.1.4 on 2021-07-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0088_member_email_machtiging'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='factuur_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
