# Generated by Django 3.1.4 on 2021-07-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0089_contribution_factuur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name='inschrijving',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name='machtiging',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name='member',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name='note',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='jarrbo_contributie.member'),
        ),
    ]
