# Generated by Django 3.1.4 on 2021-07-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0090_auto_20210727_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='regular',
            field=models.BooleanField(default=True, help_text='part of standard proces, if not new payment must be created'),
        ),
    ]
