# Generated by Django 3.1.4 on 2021-07-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0093_auto_20210728_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
