# Generated by Django 3.1.4 on 2021-07-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0094_auto_20210728_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
