# Generated by Django 3.1.4 on 2021-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0096_auto_20210728_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='inschrijving',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
