# Generated by Django 3.1.4 on 2021-07-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0097_auto_20210728_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='mail_from',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='mail_host',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='mail_password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='mail_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='mail_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='mail_username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
