# Generated by Django 3.1.4 on 2021-07-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0099_payment_withdrawnmaildate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='huygensmaildate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
