# Generated by Django 3.1.4 on 2021-08-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0100_payment_huygensmaildate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memberstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
    ]
