# Generated by Django 3.1.4 on 2021-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0101_memberstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberstatus',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
