# Generated by Django 3.1.4 on 2021-08-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0103_remove_member_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.memberstatus'),
        ),
    ]
