# Generated by Django 3.1.4 on 2021-08-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0104_member_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='contribution_payed',
        ),
    ]
