# Generated by Django 3.1.4 on 2021-08-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0105_remove_contribution_contribution_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jarrbo_contributie.paymentmethod'),
        ),
    ]
