# Generated by Django 3.1.4 on 2021-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0106_member_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activities',
            field=models.ManyToManyField(null=True, to='jarrbo_contributie.Activity'),
        ),
    ]
