# Generated by Django 3.1.4 on 2021-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0107_member_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='activities',
            field=models.ManyToManyField(to='jarrbo_contributie.Activity'),
        ),
    ]
