# Generated by Django 3.1.4 on 2021-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0108_auto_20210811_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='actie',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
