# Generated by Django 3.1.4 on 2021-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0109_paymentstatus_actie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='actie',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
