# Generated by Django 3.1.4 on 2021-08-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0110_auto_20210813_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatuschange',
            name='standard',
            field=models.BooleanField(default=True),
        ),
    ]
