# Generated by Django 3.1.4 on 2021-08-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0111_paymentstatuschange_standard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributiontable',
            options={'verbose_name': 'contribution amount', 'verbose_name_plural': 'contribution amounts'},
        ),
        migrations.AlterModelOptions(
            name='inschrijving',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='machtiging',
            options={'verbose_name': 'authority', 'verbose_name_plural': 'authorities'},
        ),
        migrations.AlterModelOptions(
            name='memberstatus',
            options={'verbose_name': 'member status', 'verbose_name_plural': 'member statuses'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentbatchstatus',
            options={'verbose_name': 'paymentbatch status', 'verbose_name_plural': 'paymentbatch statuses'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name': 'payment status', 'verbose_name_plural': 'payment statuses'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatuschange',
            options={'verbose_name': 'payment status change', 'verbose_name_plural': 'payment status changes'},
        ),
        migrations.AlterUniqueTogether(
            name='contributiontable',
            unique_together=set(),
        ),
    ]
