# Generated by Django 3.1.4 on 2021-08-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0112_auto_20210818_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributiontable',
            options={'ordering': ['seizoen', 'activity', 'leeftijdscategorie'], 'verbose_name': 'contribution amount', 'verbose_name_plural': 'contribution amounts'},
        ),
        migrations.AlterUniqueTogether(
            name='contributiontable',
            unique_together={('seizoen', 'activity', 'leeftijdscategorie')},
        ),
    ]
