# Generated by Django 3.1.4 on 2021-08-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0113_auto_20210818_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='aanvraagnummer',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='factuurnummer',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
