# Generated by Django 3.1.4 on 2021-08-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0114_auto_20210827_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='last_factuurnummer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
