# Generated by Django 3.1.4 on 2021-08-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0115_configuration_last_factuurnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='aanvraagnummer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CoronaRestitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payed', models.BooleanField(default=False)),
                ('contribution', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.contribution')),
            ],
        ),
    ]
