# Generated by Django 3.1.4 on 2021-08-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0116_auto_20210830_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronarestitution',
            name='applicable',
            field=models.BooleanField(default=False),
        ),
    ]
