# Generated by Django 3.1.4 on 2021-09-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0117_coronarestitution_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='machtiging',
            name='email_machtiging',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email_machtiging',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
