# Generated by Django 3.1.4 on 2021-09-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0119_auto_20210903_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coronarestitution',
            old_name='s_2022',
            new_name='s_2122',
        ),
    ]
