# Generated by Django 3.1.4 on 2021-09-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0121_auto_20210905_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
    ]
