# Generated by Django 3.1.4 on 2021-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0122_auto_20210906_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='factuur_adres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='factuur_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='factuur_naam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='factuur_plaats',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='factuur_postcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
