# Generated by Django 3.1.4 on 2021-09-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0123_auto_20210907_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coronarestitution',
            name='s_2122',
        ),
    ]
