# Generated by Django 3.1.4 on 2021-09-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0124_remove_coronarestitution_s_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatuschange',
            name='recovery',
            field=models.BooleanField(default=False),
        ),
    ]
