# Generated by Django 3.1.4 on 2021-09-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0125_paymentstatuschange_recovery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['datetime'], 'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
    ]
