# Generated by Django 3.1.4 on 2021-09-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0126_auto_20210923_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-datetime'], 'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['seizoen', 'contribution__member__achternaam', 'contribution__member__tussenvoegsels', 'contribution__member__roepnaam', 'paymentdate', 'paymentbatch__datum'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
