# Generated by Django 3.1.4 on 2021-09-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0127_auto_20210927_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['seizoen', 'contribution__member__achternaam', 'contribution__member__tussenvoegsels', 'contribution__member__roepnaam', 'paymentbatch__datum', 'paymentdate'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
