# Generated by Django 3.1.4 on 2021-10-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0128_auto_20210927_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='machtigingsingsdatum',
            field=models.DateField(null=True),
        ),
    ]
