# Generated by Django 3.1.4 on 2021-10-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0129_member_machtigingsingsdatum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='machtigingsingsdatum',
            new_name='machtigingsdatum',
        ),
    ]
