# Generated by Django 3.1.4 on 2021-10-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0130_auto_20211018_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='inschrijvingsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='machtigingsdatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
