# Generated by Django 3.1.4 on 2021-10-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0131_auto_20211018_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='kenmerk_machtiging',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
