# Generated by Django 3.1.4 on 2022-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0132_member_kenmerk_machtiging'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
