# Generated by Django 3.1.4 on 2022-07-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0133_contribution_received'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('member', 'seizoen', 'activity')},
        ),
    ]
