# Generated by Django 3.1.4 on 2022-08-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0135_auto_20220801_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reversalerrorcode',
            options={'ordering': ['error_code'], 'verbose_name': 'errorcode reversal', 'verbose_name_plural': 'errorcode reversals'},
        ),
        migrations.AddField(
            model_name='payment',
            name='reversalerrorcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jarrbo_contributie.reversalerrorcode'),
        ),
        migrations.AddField(
            model_name='reversalerrorcode',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
