# Generated by Django 3.1.4 on 2022-08-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0136_auto_20220801_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReversalErrorCode',
            new_name='PaymentStatusCode',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='reversalerrorcode',
            new_name='paymentstatuscode',
        ),
    ]
