# Generated by Django 3.1.4 on 2022-08-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0138_paymentstatuscode_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatuscode',
            name='paymentstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='jarrbo_contributie.paymentstatus'),
        ),
    ]
