# Generated by Django 3.1.4 on 2022-08-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0139_auto_20220802_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstatuscode',
            options={'ordering': ['status_code'], 'verbose_name': 'payment status code', 'verbose_name_plural': 'payment status codes'},
        ),
        migrations.RenameField(
            model_name='paymentstatuscode',
            old_name='error_code',
            new_name='status_code',
        ),
    ]
