# Generated by Django 3.1.4 on 2022-08-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0140_auto_20220803_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='jarrbo_contributie.activity'),
        ),
    ]
