# Generated by Django 3.1.4 on 2022-08-19 17:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0141_auto_20220819_1859'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contributiontable',
            managers=[
                ('seizoen_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('seizoen_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentbatch',
            managers=[
                ('seizoen_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
