# Generated by Django 4.2.4 on 2023-09-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0143_configuration_contributie_iban_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoronaRestitution',
        ),
    ]
