# Generated by Django 5.0.7 on 2024-08-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_contributie', '0144_delete_coronarestitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='iban_volgnr',
            field=models.IntegerField(default=0),
        ),
    ]
